services:
  postgres:
    image: postgres:latest
    container_name: postgres-profile-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: profiling_db
    ports:
      - "5433:5432"
    networks:
      - app-network
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-profile-service
    environment:
      PGADMIN_DEFAULT_EMAIL: marcopersi@me.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "3330:80"
    networks:
      - app-network

  profiling-service:
    image: profiling-service:latest
    container_name: actics-profiling-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network
    depends_on:
      - postgres

volumes:
  pg-data:

networks:
  app-network:
    driver: bridge
