services:
  postgres:
    image: postgres:latest
    container_name: postgres-profile-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: profiling_db
    ports:
      - "5433:5432"
    networks:
      - pg-network
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-profile-service
    environment:
      PGADMIN_DEFAULT_EMAIL: marcopersi@me.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "3330:80"
    networks:
      - pg-network

  app:
    image: actics-fidleg-profiling-service:latest
    container_name: profiling-service-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/profiling_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - pg-network
    depends_on:
      - postgres

volumes:
  pg-data:

networks:
  pg-network:
    driver: bridge
