spring:
  config:
    import: "classpath:database.properties"
  datasource:
    url: ${db.url}
    driver-class-name: org.postgresql.Driver
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: none
  jooq:
    sql-dialect: POSTGRES
  logging:
    level:
      org.jooq.tools.LoggerListener: DEBUG
      org.springframework.jdbc: DEBUG
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs