spring:
  springdoc:
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
    api-docs:
      path: /v3/api-docs
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jooq:
    sql-dialect: H2
  h2:
    console:
      enabled: true
      path: /h2-console