spring:
  config:
    import: optional:classpath:database-${spring.profiles.active}.properties
  datasource:
    url: ${spring.datasource.url}
    driver-class-name: org.postgresql.Driver
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: none
  jooq:
    sql-dialect: POSTGRES
  logging:
    level:
      org.jooq.tools.LoggerListener: DEBUG
      org.springframework.jdbc: DEBUG
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs